addproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .views import addprojects, projects, project, category, get_category_pro, tag, feature_project, ProjectView

app_name = 'project'

urlpatterns = [
    path('', projects, name='viewall'),
    path('<int:id>', project, name='viewone'),
    path('addproject', addprojects, name='add'),
    path('addcategory', category, name='addcategory'),
    path('feature', feature_project, name='feature'),
    path('addtag', tag, name='addtag'),
    path('category/<int:id>', get_category_pro, name='project_categories'),
    path('api', ProjectView.as_view()),

]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.home, name='home'),
    path('search', views.search_all, name='project_search'),

    # path('home/category/<int:categoty_id>', views.category, name='category')
    #path('search/', views.SearchResultsView.as_view(), name='search_results'),
]

iti_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts import views

urlpatterns = [
    # path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('project/', include('addproject.urls')),
    path('',views.test,name="land"),
    path('home/',include('home.urls'),name = 'home')
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
# from django.db.models import Q
# from django.views.generic import ListView
from addproject.views import get_project_data_for_view, projects
from django.db.models.aggregates import Count
from django.shortcuts import get_object_or_404, redirect, render
from addproject.models import Project, ProjectPics, ProjectsCategory
from django.db.models import Avg


# # Create your views here.
app_name = 'home'

'''def index(request):
    context = {
        'latest_featured': get_latest_featured_projects(),
        'get_latest_projects': get_latest_projects(),
    }

    return render(request, 'home/index.html', context)


def get_latest_featured_projects():
    model = Project.objects.order_by('-start_time')
    latest_featured_projects = get_project_data_for_view(model)
    return latest_featured_projects


def get_latest_projects():
    # returns 5 latest 5 projects based on start_date
    latest_projects_model = Project.objects.order_by('-start_time')[:5]
    latest_projects_for_view = get_project_data_for_view(latest_projects_model)
    return latest_projects_for_view


def showCategoryProjects(request, cat_id):
    c = get_object_or_404('Categories', pk=cat_id)
    category_projects = c.projects_set.all()
    project_pics2 = {}

    for p in category_projects:
        project_pics = ProjectPics.objects.filter(project=p.id)
        project_pics2[p.id] = project_pics[0]
    context = {
        'category_name': c.title,
        'c': c,
        'category_projects': category_projects,
        'pics': project_pics2
    }
    return render(request, "viewCategory.html", context)


class SearchResultsView(ListView):
    model = Project
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        model = Project.objects.filter(
            Q(title__icontains=query) | Q(category__name__icontains=query)
        ).distinct()
        object_list = projects(model)
        return object_list
'''


def home(request):
    categories = ProjectsCategory.objects.all()
    latest = Project.objects.order_by('-created_at')[:5]
    ProjectRate = Project.objects.order_by('-avg_rate')[:5]
    top_featured = Project.objects.filter(
        featured=True).order_by('-start_time')[:5]
    # print(ProjectRate)
    context = {'categories': categories,
               'latest': latest,
               'highest_rated': ProjectRate,
               'top_featured': top_featured,
               }
    return render(request, 'home/home.html', context)


def search_all(request):
    categories = ProjectsCategory.objects.all()
    if request.method == "GET":
        # check if there is a key to search by
        search_key = request.GET.get('key')

        if search_key:

            # matched by title
            matched_by_title = Project.objects.filter(
                title__icontains=search_key)

            context = {"matched_by_title": matched_by_title,
                       "key": search_key, "categories": categories}

            return render(request, 'home/search_results.html', context)

        # return to the same page if no params are passed
        return redirect(request.META.get('HTTP_REFERER', 'home'))


# def category(request, categoty_id):

#     if request.method == "GET":

#         categories = ProjectsCategory.objects.all()
#         category = get_object_or_404(ProjectsCategory, id=categoty_id)
#         projects = Project.objects.filter(category=categoty_id)
#         context = {"projects": projects,
#                    "category": category, "categories": categories}
#     return render(request, 'home/category.html', context)

home/templates/home/category.html
<!-- {% extends 'base.html' %}

{% block content %}
<h2 class="mt-5 ml-3"> Projects in {{category}} fundraising </h2>
<hr>
<div class="mt-5 mb-5 container ">
  <div class="container">
    {% if projects %}
    {% for p in projects %}

    <div class="ml-5 col-3 card card-stats mb-4 mb-xl-4 text-center h-100 shadow">

      <h3 class="card-header">{{p.title}}</h3>
      <img class="card-img-top" src="" alt="Campaign image">
      <div class="card-body">
        <h5>Target: {{p.total_target}} </h5>
        <p class="card-text cut-text ">{{p.details}}</p>
        <h5 class="card-text cut-text mb-3">By: {{p.user}}</h5>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h3 class="text-center mt-5"> There are no running projects for this fundraising right now!</h3>
    {% endif %}
  </div>
</div>
{% endblock content %} -->

home/templates/home/home.html
{% extends 'base.html' %}
{% block content %}
<form method="GET" autocomplete="off" action="{% url 'home:project_search' %}"
    class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
    {% csrf_token %}

    <div id="focusArea" class="form-group mb-5 mx-auto ">
        <div class="search-area">
            <h2 class="mt-2">Search For Projects.. </h2>
            <div class="input-group input-group-alternative">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                </div>
                <input class="form-control" id="searchBar" name="key" placeholder="Find Project By Name" type="text">
            </div>
        </div>
    </div>
</form>
<section class="content ">
    <div class="staff-picks-content">
        <h1 class="text-center mb-5 text-info">Highest Rated Projects</h1>
        <div class="staff-picks-slider slider-controls-top owl-carousel">
            {% for project in highest_rated %}
            <div class="staff-picks-item clearfix">
                <a class="staff-picks-image col-md-6 col-12" href="{%  url 'project:viewone' project.project_id %}">
                    <img style="max-height:300px;min-height:300px"
                        src="../../../media/images/{{project.picture}}"
                        alt="">
                </a>
                <div class="bg-light text-black"
                    style="padding:8px;border:.5px solid #555;border-radius:5px;max-height:250px;min-height:200px">
                    <h3 class="text-primary">
                        Project-Title: <a href="{%  url 'project:viewone' project.project_id %}">{{ project.title }}</a>
                    </h3>
                    <div class="staff-picks-description">
                        <p>Total-target: {{ project.total_target }}</p>
                        <p">Project-Details: {{ project.details }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="container-fluid mt-3">
        <div class="row  mt-4">
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-0">
                        <h2 class="card-title text-info font-weight-bold">Latest project</h2>

                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                                <tr>
                                    <th>Project</th>
                                    <th>Category</th>
                                    <th>Rates</th>
                                    <th>More</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for latest in latest %}
                                <tr>
                                    <td>
                                        {{ latest.title }}
                                    </td>
                                    <td>{{latest.category}}</td>
                                    <td>
                                        <small class="text-success mr-1">
                                            <i class="fas fa-arrow-up"></i>
                                            {{latest.avg_rate}}
                                        </small>
                                    </td>
                                    <td>
                                        <a href="{%  url 'project:viewone' latest.project_id %}" class="text-muted">
                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-0">
                        <h3 class="card-title text-info font-weight-bold">Feature projects</h3>

                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                                <tr>
                                    <th>Project</th>
                                    <th>Category</th>
                                    <th>Ratings</th>
                                    <th>More</th>
                                </tr>
                            </thead>
                            <tbody>

                                {% for feat_project in top_featured %}
                                <tr>
                                    <td>
                                        {{feat_project.title}}
                                    </td>
                                    <td>{{feat_project.category}}</td>
                                    <td>
                                        <small class="text-success mr-1">
                                            <i class="fas fa-arrow-up"></i>
                                            {{feat_project.avg_rate}}
                                        </small>
                                    </td>
                                    <td>
                                        <a href="{%  url 'project:viewone' feat_project.project_id %}"
                                            class="text-muted">

                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-0">
                        <h3 class="card-title text-info font-weight-bold">Projects Category</h3>

                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                                <tr>
                                    <th>Category</th>
                                    <th>More</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for category in categories %}
                                <tr>
                                    <td>
                                        {{category.category}}
                                    <td>
                                        <a href="{% url 'project:project_categories' category.id %}" class="text-muted">
                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <h2>Search</h2>
    <form action="{% url 'search_results' %}" method="get">
        <input name="q" type="text" placeholder="Search...">
    </form>
</div>
<div class="staff-picks mt-5">
    <div class="container-fluid">
        <div class="border-title">
            <h2 class="title left-title">Highest Rated Projects</h2>
            <div class="description left-description">The highest rated projects that are currently active
            </div>
        </div>
        <div class="owl-carousel">
            <div class="item">
                <a href="#">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
                    <div class="inner">
                        <a href="#">The Erling Bag</a>
                    </div>
                </a>
            </div>
            <div class="item black">
                <a href="#">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
                    <div class="inner">
                        <a href="#">Summer Book Series</a>
                    </div>
                </a>
            </div>
            <div class="item">
                <a href="#">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
                    <div class="inner">
                        <a href="#">The Erling Bag</a>
                    </div>
                </a>
            </div>
            <div class="item black">
                <a href="#">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
                    <div class="inner">
                        <a href="#">Summer Book Series</a>
                    </div>
                </a>
            </div>
            <div class="item">
                <a href="#">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_bags.jpg" alt="" />
                    <div class="inner">
                        <a href="#">The Erling Bag</a>
                    </div>
                </a>
            </div>
            <div class="item black">
                <a href="#">
                    <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/43033/slider_book_cover.jpg" alt="" />
                    <div class="inner">
                        <a href="#">Summer Book Series</a>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="latest campaign mt-5">
    <div class="container-fluid">
        <h2 class="title">Latest Featured Projects</h2>
        <div class="description">Recently created projects.</div>
        <div class="campaign-content">
            <div class="row">
                {% for project in latest_featured %}
                <div class="col-lg-4 col-sm-6 col-6">
                    <div class="campaign-item">
                        <div class="campaign-box">
                            <a href="#" class="category">{{ project.project_id }}</a>
                            <div class="campaign-description"> {{ project.project_details }}</div>
                            <div class="campaign-author">
                                <a class="author-icon" href="#">
                                    <img src="{{ project.project_owner_img }}" alt="">
                                </a>
                                <a class="author-name" href="#">
                                    <span>by</span>{{ project.project_title }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="latest campaign mt-5">
    <div class="container-fluid">
        <h2 class="title">Latest Five Projects</h2>
        <div class="description">Recently created projects.</div>
        <div class="campaign-content">
            <div class="row">
                {% for project in get_latest_projects %}
                <div class="col-lg-4 col-sm-6 col-6">
                    <div class="campaign-item">
                        <div class="campaign-box">
                            <a href="#" class="category">{{ project.project_category }}</a>
                            <div class="campaign-description"> {{ project.project_details }}</div>
                            <div class="campaign-author">
                                <a class="author-icon" href="#">
                                    <img src="{{ project.project_owner_img }}" alt="">
                                </a>
                                <a class="author-name" href="#">
                                    <span>by</span>{{ project.project_user }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt-5">
    <h2> Our Categories </h2>
    <div class="row">
        {% for c in categories %}
        <div class="categs">
            <a href="{% url 'show_cate' c.id %}">
                <h5 class="card-title" style="text-align: center;">{{c.title }}</h5>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

home/templates/home/search_results.html
{% extends 'base.html'%}



{% block content %}
<h1 class="m-5"> Search Results for '{{key}}'</h1>

<div class="container ">
  <hr class="w-100">

  <h2>Matches by Title </h2>
  <div class="mt-5 mb-5 container ">

    <div class="container">
      {% if matched_by_title %}

      <div class="container">
        <div class="row">
          {% for project in matched_by_title %}
          <div class="ml-5 col-3 card card-stats mb-4 mb-xl-4 text-center h-100 shadow">

            <h3 class="card-header">{{project.title}}</h3>
            <img class="card-img-top" src="../../../media/images/{{project.picture}}" alt="project image">
            <div class="card-body">
              <h5 class="card-text cut-text mb-3">By: {{project.user}}</h5>
              <h5>Target: {{project.total_target}} </h5>
              <p class="card-text cut-text ">Details: {{project.details}}</p>
            </div>
          </div>

          {% endfor %}
        </div>
      </div>
      {% else %}
      <h3 class="text-center mt-5"> No matches found!</h3>
      {% endif %}
    </div>
  </div>


  {% endblock %}