addproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .views import addprojects, projects, project, category, get_category_pro, tag, feature_project, ProjectView

app_name = 'project'

urlpatterns = [
    path('', projects, name='viewall'),
    path('<int:id>', project, name='viewone'),
    path('addproject', addprojects, name='add'),
    path('addcategory', category, name='addcategory'),
    path('feature', feature_project, name='feature'),
    path('addtag', tag, name='addtag'),
    path('category/<int:id>', get_category_pro, name='project_categories'),
    path('api', ProjectView.as_view()),

]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.home, name='home'),
    path('search', views.search_all, name='project_search'),

    # path('home/category/<int:categoty_id>', views.category, name='category')
    #path('search/', views.SearchResultsView.as_view(), name='search_results'),
]

iti_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts import views

urlpatterns = [
    # path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('project/', include('addproject.urls')),
    path('',views.test,name="land"),
    path('home/',include('home.urls'),name = 'home')
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{%block head%}
        {% include "head.html" %}
    {%endblock head%}

    <body class="hold-transition sidebar-mini layout-fixed " style="background-color: #F4F6F9; margin: 0">
    {%block navbar%}
        {% include "nav.html" %}
    {%endblock navbar%}
    {%block sidebar%}
        {% include "sidebar.html" %}
    {%endblock sidebar%}

 <div class="content-wrapper">
            <!-- Content Header (Page header) -->

    {%block content%}
    {%endblock content%}





{%block footer%}
{% include "footer.html" %}
{%endblock footer%}

{%block scripts%}
{% include "scripts.html" %}
{%endblock scripts%}
{%block js%}
{%endblock js%}
     </body>

</html>

templates/footer.html
{% load static %}
{%block footer%}
</div>
<footer class="main-footer ">

    <div class="copyright-bar clearfix">
        <div class="row">
            <div class="col-lg-6">
                <div class="copy-text"><strong>Copyright &copy; 2021 <a href="#"> ITI Team</a>.</strong> All
                    rights
                    reserved.

                </div>
            </div>
        </div>
    </div>
</footer>
</div>
<!-- ./wrapper -->

<!-- jQuery -->


<form method="post" action="#" class="modal fade text-left confirm-modal" id="danger" tabindex="-1" role="dialog"
    aria-labelledby="Confirmation Modal" aria-hidden="true" style="display: none;">
    {% csrf_token %}
    <input type="hidden" name="">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header  white">
                <h5 class="modal-title" id="model-confirm-header">Confirm Process ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" id="modal-confirm-body">

                Do you want delete this ?
            </div>
            <div class="modal-footer d-flex">
                <button type="submit" class="btn btn-danger waves-effect waves-light">delete</button>
            </div>
        </div>
    </div>
</form>

{%endblock footer%}

templates/head.html
{% block head %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/toastr/toastr.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'assets/dist/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
        integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="{% static 'assets/plugins/fullcalendar/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/fullcalendar-daygrid/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/fullcalendar-timegrid/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/fullcalendar-bootstrap/main.min.css' %}">
    <!-- overlayScrollbars -->


    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
{% endblock head %}

templates/nav.html
{% load static %}
{%block navbar%}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>

    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item ">
                <a class="nav-link" href="{% url 'logout' %}" role="button">
                    <i class="fas fa-sign-out-alt"></i>
                    Logout
                </a>
            </div>
        </li>
        <li></li>

    </ul>
</nav>
{%endblock navbar%}

templates/scripts.html
{% load static %}


<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
<script src="	https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.1.135/jspdf.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/plugins/toastr/toastr.min.js' %}"></script>


<!-- AdminLTE App -->
<script src="{% static 'assets/dist/js/adminlte.min.js' %}"></script>

<script src="{% static 'assets/plugins/chart.js/Chart.min.js' %}"></script>

<!-- AdminLTE for demo purposes -->
<script src="{% static 'assets/dist/js/demo.js' %}"></script>
<script src="{% static 'assets/dist/js/main.js' %}"></script>
<script src="{% static 'assets/dist/js/jspdf.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
    integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $('.owl-carousel').owlCarousel({
        loop: true,
        autoplay: true,
        margin: 10,
        navigation: false,
        responsive: {
            0: {
                items: 1
            },
            600: {
                items: 2
            },
            1000: {
                items: 3
            }
        }
    })

</script>

templates/search_results.html
{% extends 'base.html' %}
{% block body %}
<div class="page-title background-page">
    <div class="container">
        <h1>Search Results</h1>
        <div class="breadcrumbs">
            <ul>
                <li><a href="index.html">Home</a><span>/</span></li>
                <li>Search results</li>
            </ul>
        </div><!-- .breadcrumbs -->
    </div>
</div><!-- .page-title -->
<div class="campaigns">
    <div class="container">
        <div class="campaign-content">
            <div class="row">
                <div class="col-lg-4 col-sm-6 col-6">
                    <div class="campaign-item">
                        <div class="campaign-box">
                            <a href="#" class="category"></a>
                            <h3><a href="#"></a></h3>
                            <div class="campaign-description"></div>
                            <div class="campaign-author">
                                <a class="author-icon" href="#">
                                    <img src="" alt="">
                                </a>by
                                <a class="author-name" href="#"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/sidebar.html
{% load static %}
{% block sidebar %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/project" class="brand-link">
        <img src="{% static 'assets/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Crowd-Fund</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->

        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            {% if user.profile.avatar %}
            <div class="image">
                <img src="{{ request.user.profile.img.url }} " class="img-circle elevation-2">
            </div>
            {% else %}
            <div class="image">
                <img class="img-circle elevation-2" style="max-height: 80px; width: 80px"
                    src="https://via.placeholder.com/128" alt="">
            </div>
            {% endif %}
            <div class="info">
                <a href="{% url 'profile' %}" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>


        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview">
                    <a href="{% url 'home:home' %}" class="nav-link">
                        <!-- <i class="nav-icon fas fa-tachometer-alt"></i> -->
                        <p>
                            Home
                        </p>
                    </a>

                </li>
                <!-- <li class="nav-item has-treeview">
                    <a href="{% url 'project:viewall' %}" class="nav-link">
                        <i class="nav-icon fas fa-tasks"></i>
                        <p>
                            Projects
                        </p>
                    </a>
                </li> -->
                <li class="nav-item has-treeview">
                    <a href="{% url 'project:add' %}" class="nav-link">
                        <!-- <i class="nav-icon fas fa-copy"></i> -->
                        <p>
                            Start Project

                        </p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="/project" class="nav-link">
                        <!-- <i class="nav-icon fas fa-users"></i> -->
                        <p>
                            Projects List
                        </p>
                    </a>
                </li>
                {% if request.user.is_superuser %}
                <li class="nav-item has-treeview">
                    <a href="{% url 'project:addcategory' %}" class="nav-link">
                        <!-- <i class="nav-icon fas fa-building"></i> -->
                        <p>
                            Add New Category

                        </p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{% url 'project:addtag' %}" class="nav-link">
                        <!-- <i class="nav-icon fas fa-building"></i> -->
                        <p>
                            Add New Tag

                        </p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="{% url 'project:feature' %}" class="nav-link">
                        <!-- <i class="nav-icon fas fa-building"></i> -->
                        <p>
                            Feature Project

                        </p>
                    </a>
                </li>
                {% endif %}

                <!-- <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-bullhorn"></i>
                        <p>
                            Tasks
                        </p>
                    </a>
                </li> -->
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>

<!-- /.control-sidebar -->
{% endblock sidebar %}

templates/viewCategory.html
{% extends "base.html" %}
{% block content %}
{% if request.user.is_authenticated %}

<div class="container">
    <h1 style="
        margin: 1em 0 0.5em 0;
        color: #343434;
        font-weight: normal;
        font-family: 'Ultra', sans-serif;
        font-size: 36px;
        line-height: 42px;
        text-transform: uppercase;
        text-shadow: 0 2px white, 0 3px #777;">
        {{category_name}}
    </h1>
    <div class="row">
        {% for project in category_projects %}
        <div class="col-sm-4 mt-5">
            <div class="card" style="width: 18rem;">
                <a href="{% url 'projects:project_page' project.id %}">
                    <img src="/media/{{pics|get_item:project.id}}" class="card-img-top"
                        style="width:100%; height:100px;">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{project.title}}</h5>
                    <p class="card-text">{{project.details}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}